export const projects = [
  {
    id: 1,
    title: "AI Chat Application",
    description: "AI-powered team collaboration platform",
    technology: "React + Node.js",
    progress: 80,
    members: 5,
    status: "In Progress",
  },
  {
    id: 2,
    title: "CRM Dashboard",
    description: "Customer relationship management system",
    technology: "MERN Stack",
    progress: 45,
    members: 3,
    status: "Planning",
  },
  {
    id: 3,
    title: "HR Management",
    description: "Employee management portal",
    technology: "React + Firebase",
    progress: 70,
    members: 6,
    status: "Development",
  },
  {
    id: 4,
    title: "E-Commerce Store",
    description: "Online shopping application",
    technology: "React + Express",
    progress: 92,
    members: 8,
    status: "Testing",
  },
  {
    id: 5,
    title: "Project Management",
    description: "Task and team management platform",
    technology: "React + TypeScript",
    progress: 60,
    members: 4,
    status: "In Progress",
  },
  {
    id: 6,
    title: "Learning Portal",
    description: "Online course management system",
    technology: "React + MongoDB",
    progress: 35,
    members: 7,
    status: "Planning",
  },
];